name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}   # Use the personal token (instead of GITHUB_TOKEN)
          publish_dir: ./dist
          force_orphan: true
          user_name: 'Ashish-1521'                  # Optional: set your username for commit
          user_email: 'ashish.thatipalli@gmail.com'    # Optional: set your email for commit
          target_branch: gh-pages                 # Ensure deployment goes to gh-pages branch
          repository_name: Ashish-1521/portfolio # Make sure to set the repo name (new public repo)
